evesso:
  client:
    #local
    #    clientId: f6cfa86f89654ee2b3cd1fe369ba4c33
    #    clientSecret: ajYLIIzjcgGPdwKjbnKl7wzKShAq5FMwU9DCRwQZ
    #dev.wst-eve.website
    clientId: 55df9334f37e4e96a0e373bfe621658c
    clientSecret: iylulvPNU422wL9xrynoze5chVznoJxTGXivIVls
    accessTokenUri: https://login.eveonline.com/oauth/token
    userAuthorizationUri: https://login.eveonline.com/oauth/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: publicData
  resource:
    userInfoUri: https://login.eveonline.com/oauth/verify

logging:
  level:
    org.wst: DEBUG
#    org.springframework.http.converter: TRACE
#    org.springframework.web.client: DEBUG
  file: application.log

spring:
  resources:
    chain:
      enabled: true
  datasource:
    jndi-name: java:jboss/datasources/PostgreSQLDS
    

      