evesso:
  client:
    clientId: f6cfa86f89654ee2b3cd1fe369ba4c33
    clientSecret: ajYLIIzjcgGPdwKjbnKl7wzKShAq5FMwU9DCRwQZ
    accessTokenUri: https://login.eveonline.com/oauth/token
    userAuthorizationUri: https://login.eveonline.com/oauth/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: publicData
  resource:
    userInfoUri: https://login.eveonline.com/oauth/verify


spring:
  resources:
    chain:
      enabled: true
      
      
      